[package]
name = "solar_system_ephemeris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj = "0.10.2"
serde_json = "1.0.82"
serde = "1.0.139"
serde_derive = "1.0.139"